# Generated by Django 2.2.5 on 2019-09-21 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('D', 'Driver'), ('U', 'User'), ('C', 'CC Admin')], default='U', max_length=2),
        ),
    ]
