# Generated by Django 2.2.5 on 2019-09-21 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('P', 'Placed'), ('U', 'Picked Up'), ('T', 'In Transist'), ('R', 'Recieved at collection center')], max_length=1)),
                ('weight', models.IntegerField()),
                ('date_of_order', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='WasteType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
