# Generated by Django 2.2.5 on 2019-09-21 14:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='assigned_driver',
            field=models.ForeignKey(limit_choices_to={'user_type': 'D'}, on_delete=django.db.models.deletion.PROTECT, related_name='Driver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='user_details',
            field=models.ForeignKey(limit_choices_to={'user_type': 'U'}, on_delete=django.db.models.deletion.PROTECT, related_name='User', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='order',
            name='waste_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='order.WasteType'),
        ),
    ]
